export const Tutors = [
  {
    id: 1,
    username: "James Wilson",
    firstName: "James",
    lastName: "Wilson",
    phoneCode: "+1",
    phoneNumber: "5551234567",
    email: "james.wilson@example.com",
    bio: "Certified handyman with over 10 years of experience in home repairs and solar systems.",
    avatar:
      "https://images.generated.photos/hTWhfPc0WQUwABdQHBpgtOCTXeZ-cKtJYUQ6cQy_Bbc/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/NDk4NTA5LmpwZw.jpg",
    skills: ["Plumbing", "Solar Installation", "Tile Setting", "HVAC Repair"],
  },
  {
    id: 2,
    username: "Amelia Johnson",
    firstName: "Amelia",
    lastName: "Johnson",
    phoneCode: "+44",
    phoneNumber: "7700123456",
    email: "amelia.johnson@example.co.uk",
    bio: "Vocational trainer in sustainable construction and carpentry, focused on empowering youth.",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJ7Z4MkaCNHvhNt9hbrThPRtfMqP-DHJEJXO2LrsRyGeNWoEz7QKr1GBmbpEvZ0wUMf8k&usqp=CAU",
    skills: ["Green Building", "Woodworking", "Electrical Safety", "Carpentry"],
  },
  {
    id: 3,
    username: "Daniel Kim",
    firstName: "Daniel",
    lastName: "Kim",
    phoneCode: "+82",
    phoneNumber: "1023456789",
    email: "daniel.kim@example.kr",
    bio: "Electrical specialist with a passion for teaching hands-on technology and wiring systems.",
    avatar:
      "https://i.pinimg.com/736x/d0/4a/77/d04a77de6cc535e9163a3892f66c607d.jpg",
    skills: [
      "Circuit Design",
      "Electrical Wiring",
      "Power Tools Operation",
      "Basic Robotics",
    ],
  },
  {
    id: 4,
    username: "Sophia Brown",
    firstName: "Sophia",
    lastName: "Brown",
    phoneCode: "+61",
    phoneNumber: "412345678",
    email: "sophia.brown@example.au",
    bio: "Enthusiastic about vocational education, with a strong background in carpentry and design.",
    avatar:
      "https://images.generated.photos/dqgFfi6eDIDlBGOB2zvBNV4szln8-shFtQgOqOirpeA/g:no/rs:fill:256:384/czM6Ly9ncGhvdG9z/LXByb2QtaHVtYW4t/Z2FsbGVyeS80NzAv/NDE4NDBjZjYtMjYz/NS00ZGIyLWFhZjMt/YzAyNDU2Mzk2ZTk4/LTAuanBn.jpg",
    skills: [
      "Furniture Making",
      "Interior Fittings",
      "Wood Joinery",
      "3D Modeling",
    ],
  },
  {
    id: 5,
    username: "Liam Smith",
    firstName: "Liam",
    lastName: "Smith",
    phoneCode: "+27",
    phoneNumber: "831234567",
    email: "liam.smith@example.co.za",
    bio: "Skilled vocational instructor focused on solar systems and rural electrification training.",
    avatar:
      "https://img.freepik.com/premium-photo/illustration-backpacker-man-abstract-art-ai-generated_57312-1520.jpg",
    skills: [
      "Solar Panel Installation",
      "Battery Systems",
      "Welding",
      "Roofing",
    ],
  },
  {
    id: 6,
    username: "Olivia Garcia",
    firstName: "Olivia",
    lastName: "Garcia",
    phoneCode: "+34",
    phoneNumber: "612345678",
    email: "olivia.garcia@example.es",
    bio: "Expert in plumbing and sanitation systems, committed to clean water initiatives.",
    avatar:
      "https://media.istockphoto.com/id/1386479313/photo/happy-millennial-afro-american-business-woman-posing-isolated-on-white.jpg?s=612x612&w=0&k=20&c=8ssXDNTp1XAPan8Bg6mJRwG7EXHshFO5o0v9SIj96nY=",
    skills: [
      "Pipe Fitting",
      "Drainage Systems",
      "Sanitation Design",
      "Water Pump Installation",
    ],
  },
];